name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        version: [
            { python: "3.7", ubuntu: "ubuntu-22.04" },
            { python: "3.8", ubuntu: "ubuntu-22.04" },
            { python: "3.9", ubuntu: "ubuntu-latest" },
            { python: "3.10", ubuntu: "ubuntu-latest" },
            { python: "3.11", ubuntu: "ubuntu-latest" },
            { python: "3.12", ubuntu: "ubuntu-latest" } ]
    runs-on: ${{ matrix.version.ubuntu }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Kerberos
      run: sudo apt-get install -y libkrb5-dev krb5-kdc krb5-admin-server
    - name: Set up Python ${{ matrix.version.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version.python }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make deps
    - name: Test
      run: |
        make test
    - name: Lint
      if: matrix.version.python != '3.7'
      run: |
        make lint
    - name: Format
      if: matrix.version.python != '3.7'
      run: |
        make format-check
    - name: Type annotations
      if: matrix.version.python != '3.7'
      run: |
        make types
  mysql-connector-j:
    name: Integration (mysql-connector-j)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Kerberos
      run: sudo apt-get install -y libkrb5-dev krb5-kdc krb5-admin-server
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: setup.py
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        make deps
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Test mysql-connector-j
      run: |
        python integration/run.py integration/mysql-connector-j/
