name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Kerberos
      run: sudo apt-get install -y libkrb5-dev krb5-kdc krb5-admin-server
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make deps
    - name: Test
      run: |
        make test
    - name: Lint
      run: |
        make lint
    - name: Format
      run: |
        make format-check
    - name: Type annotations
      run: |
        make types
  mysql-connector-j:
    name: Integration (mysql-connector-j)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Kerberos
      run: sudo apt-get install -y libkrb5-dev krb5-kdc krb5-admin-server
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: setup.py
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        make deps
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Test mysql-connector-j
      run: |
        python integration/run.py integration/mysql-connector-j/
